-- Synthetic dimension table seeded at container init.
-- custkey values 1..50 align with TPCH customer keys so a federated join works.
-- All values are invented; no real customers.

CREATE TABLE IF NOT EXISTS customer_segment (
    custkey BIGINT PRIMARY KEY,
    segment TEXT NOT NULL,
    region  TEXT NOT NULL
);

INSERT INTO customer_segment (custkey, segment, region) VALUES
    (1,  'enterprise', 'north'),
    (2,  'startup',    'south'),
    (3,  'enterprise', 'east'),
    (4,  'midmarket',  'west'),
    (5,  'startup',    'north'),
    (6,  'midmarket',  'south'),
    (7,  'enterprise', 'east'),
    (8,  'startup',    'west'),
    (9,  'midmarket',  'north'),
    (10, 'enterprise', 'south'),
    (11, 'startup',    'east'),
    (12, 'midmarket',  'west'),
    (13, 'enterprise', 'north'),
    (14, 'startup',    'south'),
    (15, 'midmarket',  'east'),
    (16, 'enterprise', 'west'),
    (17, 'startup',    'north'),
    (18, 'midmarket',  'south'),
    (19, 'enterprise', 'east'),
    (20, 'startup',    'west'),
    (21, 'midmarket',  'north'),
    (22, 'enterprise', 'south'),
    (23, 'startup',    'east'),
    (24, 'midmarket',  'west'),
    (25, 'enterprise', 'north'),
    (26, 'startup',    'south'),
    (27, 'midmarket',  'east'),
    (28, 'enterprise', 'west'),
    (29, 'startup',    'north'),
    (30, 'midmarket',  'south'),
    (31, 'enterprise', 'east'),
    (32, 'startup',    'west'),
    (33, 'midmarket',  'north'),
    (34, 'enterprise', 'south'),
    (35, 'startup',    'east'),
    (36, 'midmarket',  'west'),
    (37, 'enterprise', 'north'),
    (38, 'startup',    'south'),
    (39, 'midmarket',  'east'),
    (40, 'enterprise', 'west'),
    (41, 'startup',    'north'),
    (42, 'midmarket',  'south'),
    (43, 'enterprise', 'east'),
    (44, 'startup',    'west'),
    (45, 'midmarket',  'north'),
    (46, 'enterprise', 'south'),
    (47, 'startup',    'east'),
    (48, 'midmarket',  'west'),
    (49, 'enterprise', 'north'),
    (50, 'startup',    'south');
